CREATE TABLE [dbo].[StageIncident] (
    [StudentName]     VARCHAR (50)  NULL,
    [StudentID]       VARCHAR (50)  NULL,
    [SchoolCode]      VARCHAR (50)  NULL,
    [SchoolName]      VARCHAR (50)  NULL,
    [Grade]           VARCHAR (50)  NULL,
    [IncidentCode]    VARCHAR (50)  NULL,
    [Incident]        VARCHAR (50)  NULL,
    [InvolvementCode] VARCHAR (50)  NULL,
    [Involvement]     VARCHAR (50)  NULL,
    [ReportedBy]      VARCHAR (50)  NULL,
    [IncidentDate]    VARCHAR (50)  NULL,
    [Location]        VARCHAR (50)  NULL,
    [IncidentTime]    VARCHAR (50)  NULL,
    [RefInfo]         VARCHAR (50)  NULL,
    [ActionCode]      VARCHAR (50)  NULL,
    [Action]          VARCHAR (50)  NULL,
    [Alert]           VARCHAR (50)  NULL,
    [Points]          VARCHAR (50)  NULL,
    [ReferredTo]      VARCHAR (50)  NULL,
    [Advisor]         VARCHAR (50)  NULL,
    [Counselor]       VARCHAR (50)  NULL,
    [Notes]           VARCHAR (300) NULL,
    [Column 22]       VARCHAR (50)  NULL
);

